version: '3.4'
services:
  linuxgsm:
    image: "ghcr.io/gameservermanagers/linuxgsm-docker:latest"
    container_name: rustserver
    environment:
      - GAMESERVER=rustserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - ./serverfiles:/home/linuxgsm/serverfiles
      - ./log:/home/linuxgsm/log
      - ./config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "28015:28015/tcp"
      - "28015:28015/udp"
      - "28016:28016/tcp"
      - "28016:28016/udp"
    restart: unless-stopped
