version: '3.4'

services:
  linuxgsmdocker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lgsm-docker
    environment:
      - GAMESERVER=csgoserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /path/to/serverfiles:/home/linuxgsm/serverfiles
      - /path/to/log:/home/linuxgsm/log
      - /path/to/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    network_mode: host
    restart: unless-stopped