version: '3.4'
services:
  lgsm-docker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lgsm-csgoserver
    environment:
      - GAMESERVER=csWgoserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /home/linuxgsm/serverfiles:/home/linuxgsm/serverfiles
      - /home/linuxgsm/serverfiles:/home/linuxgsm/log
      - /home/linuxgsm/serverfiles:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"
    restart: unless-stopped